"""Increase password hash length

Revision ID: 22853d719457
Revises: 2d6bd5640bc7
Create Date: 2025-02-09 11:01:10.490703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22853d719457'
down_revision = '2d6bd5640bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
