"""Add telegram notification columns

Revision ID: 2d6bd5640bc7
Revises: 05f745420da0
Create Date: 2025-02-09 10:34:24.497327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6bd5640bc7'
down_revision = '05f745420da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('telegram_notifications_enabled')

    # ### end Alembic commands ###
