"""Add price_alert_threshold to Query

Revision ID: 4c8b6fc2e9d0
Revises: 6358273dc673
Create Date: 2025-02-09 11:47:29.887191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8b6fc2e9d0'
down_revision = '6358273dc673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_alert_threshold', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('price_alert_threshold')

    # ### end Alembic commands ###
