"""Add total_items to query

Revision ID: 6358273dc673
Revises: 8496889dcef3
Create Date: 2025-02-09 11:35:18.205379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6358273dc673'
down_revision = '8496889dcef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_items', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('total_items')

    # ### end Alembic commands ###
