"""Add item activity tracking and price history

Revision ID: 8295a0745696
Revises: 22853d719457
Create Date: 2025-02-09 11:12:42.036851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8295a0745696'
down_revision = '22853d719457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('price_history')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
