"""added created_at to userqueryitems

Revision ID: 0c73b30a590c
Revises: 50256c55fe93
Create Date: 2025-03-13 20:36:19.410896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73b30a590c'
down_revision = '50256c55fe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
