"""new schema for subscriptions

Revision ID: 2262def49b5f
Revises: 7c6db238f9c8
Create Date: 2025-03-03 09:09:29.388517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2262def49b5f'
down_revision = '7c6db238f9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('requested_change', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_usage', sa.Integer(), nullable=True))
        batch_op.drop_column('query_limit')
        batch_op.drop_column('query_usage')
        batch_op.drop_column('query_limit_when_sub_ends')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_limit_when_sub_ends', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('query_usage', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('query_limit', sa.INTEGER(), nullable=True))
        batch_op.drop_column('current_usage')
        batch_op.drop_column('requested_change')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
