"""changed user_query_limit to query_limit

Revision ID: 25bffd14700f
Revises: 315926e96f26
Create Date: 2025-02-26 17:31:52.165766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bffd14700f'
down_revision = '315926e96f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_usage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('query_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('user_query_usage')
        batch_op.drop_column('user_query_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_query_limit', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_query_usage', sa.INTEGER(), nullable=True))
        batch_op.drop_column('query_limit')
        batch_op.drop_column('query_usage')

    # ### end Alembic commands ###
