"""Add telegram connection fields

Revision ID: 30376cf4acdc
Revises: c28d97f33a2f
Create Date: 2025-02-10 16:04:47.504482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30376cf4acdc'
down_revision = 'c28d97f33a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_connected')

    # ### end Alembic commands ###
