"""changed to query_usage

Revision ID: 329e9b2cbf0d
Revises: 51de0bba21c5
Create Date: 2025-03-03 11:20:02.811613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329e9b2cbf0d'
down_revision = '51de0bba21c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_usage', sa.Integer(), nullable=True))
        batch_op.drop_column('current_usage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_usage', sa.INTEGER(), nullable=True))
        batch_op.drop_column('query_usage')

    # ### end Alembic commands ###
