"""Replace lambda default with named function

Revision ID: 3b1e84814c23
Revises: aa5945a9c159
Create Date: 2025-02-24 11:36:16.360342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1e84814c23'
down_revision = 'aa5945a9c159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_full_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_full_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_recent_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('needs_scheduling', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_queries_needs_scheduling'), ['needs_scheduling'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_needs_scheduling'))
        batch_op.drop_column('needs_scheduling')
        batch_op.drop_column('last_recent_run')
        batch_op.drop_column('next_full_run')
        batch_op.drop_column('last_full_run')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
