"""Add unique constraint on ebay_id, keywords, recorded_at

Revision ID: 3ec20e7cd887
Revises: bba41e17e08e
Create Date: 2025-02-21 16:22:31.293677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec20e7cd887'
down_revision = 'bba41e17e08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ebay_id_recorded', type_='unique')
        batch_op.create_unique_constraint('uq_ebay_keywords_time', ['ebay_id', 'keywords', 'recorded_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ebay_keywords_time', type_='unique')
        batch_op.create_unique_constraint('uq_ebay_id_recorded', ['ebay_id', 'recorded_at'])

    # ### end Alembic commands ###
