"""Changed start_time and end_time to strings

Revision ID: 41929b5c6f49
Revises: 8d61198fc93d
Create Date: 2025-02-18 21:21:12.932484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41929b5c6f49'
down_revision = '8d61198fc93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=40),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=40),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
