"""added average_relevance_score

Revision ID: 50256c55fe93
Revises: f707ca360df9
Create Date: 2025-03-13 14:42:24.834424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50256c55fe93'
down_revision = 'f707ca360df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_relevance_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.drop_column('average_relevance_score')

    # ### end Alembic commands ###
