"""Changed tier to json

Revision ID: 51de0bba21c5
Revises: 2262def49b5f
Create Date: 2025-03-03 09:42:37.294283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de0bba21c5'
down_revision = '2262def49b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
