"""Added keywords and long term storage

Revision ID: 543842294967
Revises: 6d80dacbd4f1
Create Date: 2025-02-20 16:10:51.255182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543842294967'
down_revision = '6d80dacbd4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_term_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('ebay_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('seller', sa.String(length=100), nullable=True),
    sa.Column('seller_rating', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('location_country', sa.String(length=10), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('buying_options', sa.Text(), nullable=True),
    sa.Column('auction_details', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('marketplace', sa.String(length=20), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_id', 'recorded_at', name='uq_ebay_id_recorded')
    )
    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_long_term_items_keywords'), ['keywords'], unique=False)

    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_long_term_items_keywords'))

    op.drop_table('long_term_items')
    # ### end Alembic commands ###
