"""Change unique constraint to composite key

Revision ID: 54b492914804
Revises: 275ad6af4594
Create Date: 2025-02-12 12:28:22.876583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b492914804'
down_revision = '275ad6af4594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_ebay_id')
        batch_op.drop_index('ix_items_query_id')
        batch_op.create_unique_constraint('uq_ebay_id_query', ['ebay_id', 'query_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ebay_id_query', type_='unique')
        batch_op.create_index('ix_items_query_id', ['query_id'], unique=False)
        batch_op.create_index('ix_items_ebay_id', ['ebay_id'], unique=1)

    # ### end Alembic commands ###
