"""added relationship from userqueryitems to userquery

Revision ID: 589a4b863dd0
Revises: 0c73b30a590c
Create Date: 2025-03-14 08:58:35.932390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589a4b863dd0'
down_revision = '0c73b30a590c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_item_keyword_feedback', ['user_id', 'item_id', 'keyword_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_item_keyword_feedback', type_='unique')

    # ### end Alembic commands ###
