"""Added item_location to Query column

Revision ID: 66f74dbda4f2
Revises: 2e9e2a54627b
Create Date: 2025-02-10 11:40:21.033275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f74dbda4f2'
down_revision = '2e9e2a54627b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_location', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('item_location')

    # ### end Alembic commands ###
