"""Add item fields

Revision ID: 67347b8e0d88
Revises: c5240bf7a56a
Create Date: 2025-02-09 17:14:53.687250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67347b8e0d88'
down_revision = 'c5240bf7a56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ebay_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_constraint('items_ebay_item_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ebay_id'])
        batch_op.drop_column('currency')
        batch_op.drop_column('ebay_item_id')
        batch_op.drop_column('condition')
        batch_op.drop_column('price_history')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_price_change')
        batch_op.drop_column('first_seen')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_price_change', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ebay_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('items_ebay_item_id_key', ['ebay_item_id'])
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('image_url')
        batch_op.drop_column('ebay_id')

    # ### end Alembic commands ###
