"""removed original price and currency

Revision ID: 6d80dacbd4f1
Revises: e03db3e55dfa
Create Date: 2025-02-19 11:03:31.773478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d80dacbd4f1'
down_revision = 'e03db3e55dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('original_price')
        batch_op.drop_column('original_currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_currency', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
