"""added cancellation requested

Revision ID: 801ad1674e48
Revises: 9abcfb94c53d
Create Date: 2025-03-04 18:05:01.511567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801ad1674e48'
down_revision = '9abcfb94c53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cancellation_requested')

    # ### end Alembic commands ###
