"""removed categories, images and auction details

Revision ID: 8fdac930ebf0
Revises: 9b99dcd45c9d
Create Date: 2025-02-19 09:59:22.841230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdac930ebf0'
down_revision = '9b99dcd45c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('auction_details')
        batch_op.drop_column('categories')
        batch_op.drop_column('images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('auction_details', sa.TEXT(), nullable=True))

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
