"""changed schema for subscriptions in Users

Revision ID: 9abcfb94c53d
Revises: cfcd076fb1bc
Create Date: 2025-03-04 13:35:08.937945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abcfb94c53d'
down_revision = 'cfcd076fb1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.drop_column('query_usage')
        batch_op.drop_column('subscription_valid_until')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_valid_until', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('query_usage', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
