"""Add marketplace, categories, images and auction details

Revision ID: 9b99dcd45c9d
Revises: ecaf3bd89410
Create Date: 2025-02-19 09:54:37.029167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b99dcd45c9d'
down_revision = 'ecaf3bd89410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('marketplace', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('images')
        batch_op.drop_column('marketplace')
        batch_op.drop_column('categories')
        batch_op.drop_column('end_time')
        batch_op.drop_column('auction_details')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
