"""initial migration

Revision ID: 9d0d6cb6fcfb
Revises: 
Create Date: 2025-02-11 10:21:53.140376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0d6cb6fcfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_country', sa.String(length=50), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('seller_rating',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint('items_ebay_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_items_ebay_id'), ['ebay_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_query_id'), ['query_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_connected')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_query_id'))
        batch_op.drop_index(batch_op.f('ix_items_ebay_id'))
        batch_op.create_unique_constraint('items_ebay_id_key', ['ebay_id'])
        batch_op.alter_column('seller_rating',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('location_country')

    # ### end Alembic commands ###
