"""added query usage

Revision ID: aa0442f11223
Revises: 801ad1674e48
Create Date: 2025-03-05 12:09:27.365619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0442f11223'
down_revision = '801ad1674e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_usage', sa.Integer(), nullable=True))
        batch_op.drop_column('auto_renew')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_renew', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('query_usage')

    # ### end Alembic commands ###
