"""added legacy Id

Revision ID: aa5945a9c159
Revises: e286fb3150a0
Create Date: 2025-02-21 20:09:24.645802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5945a9c159'
down_revision = 'e286fb3150a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_items', schema=None) as batch_op:
        batch_op.drop_column('legacy_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('legacy_id')

    # ### end Alembic commands ###
