"""Added inheritance for long term storage

Revision ID: bba41e17e08e
Revises: 543842294967
Create Date: 2025-02-21 15:58:21.013513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba41e17e08e'
down_revision = '543842294967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_items_keywords'), ['keywords'], unique=False)
        batch_op.drop_column('legacy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_items_keywords'))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
