"""Added auto_renew

Revision ID: c047dd32f1ad
Revises: f0c3b1a61b8f
Create Date: 2025-02-27 10:24:30.000831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c047dd32f1ad'
down_revision = 'f0c3b1a61b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auto_renew')

    # ### end Alembic commands ###
