"""Add new item fields

Revision ID: c28d97f33a2f
Revises: 66f74dbda4f2
Create Date: 2025-02-10 13:40:41.514154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28d97f33a2f'
down_revision = '66f74dbda4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('original_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('seller', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seller_rating', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('listing_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('listing_date')
        batch_op.drop_column('categories')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('condition')
        batch_op.drop_column('seller_rating')
        batch_op.drop_column('seller')
        batch_op.drop_column('original_currency')
        batch_op.drop_column('original_price')
        batch_op.drop_column('legacy_id')

    # ### end Alembic commands ###
