"""Change price columns to Numeric

Revision ID: d8aa6e936942
Revises: 67347b8e0d88
Create Date: 2025-02-09 17:47:23.467426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8aa6e936942'
down_revision = '67347b8e0d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('check_interval',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.alter_column('check_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('max_price')
        batch_op.drop_column('min_price')

    # ### end Alembic commands ###
