"""changed is_relevant to allow Null values

Revision ID: dbd47fa2b01e
Revises: 589a4b863dd0
Create Date: 2025-03-14 09:27:26.219063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd47fa2b01e'
down_revision = '589a4b863dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.alter_column('is_relevant',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.alter_column('is_relevant',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
