"""Add auction and shipping fields

Revision ID: df4fa333dfaa
Revises: d1cc8ae8869e
Create Date: 2025-02-18 20:41:27.116808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4fa333dfaa'
down_revision = 'd1cc8ae8869e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bid_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_bid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('start_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shipping_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('shipping_currency')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_price')
        batch_op.drop_column('current_bid')
        batch_op.drop_column('bid_count')
        batch_op.drop_column('listing_type')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
