"""Rename item-query backref to search_query

Revision ID: e286fb3150a0
Revises: 3ec20e7cd887
Create Date: 2025-02-21 19:30:23.303327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e286fb3150a0'
down_revision = '3ec20e7cd887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
