"""changed query_id to uuid

Revision ID: e6e652fd1654
Revises: aae74aa5a0ac
Create Date: 2025-03-12 21:24:59.630153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e652fd1654'
down_revision = 'aae74aa5a0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
