"""added subscription_valid_until

Revision ID: f0c3b1a61b8f
Revises: 25bffd14700f
Create Date: 2025-02-27 10:15:36.111426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c3b1a61b8f'
down_revision = '25bffd14700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_valid_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_valid_until')

    # ### end Alembic commands ###
