"""changed query_id to string uuid

Revision ID: f114a23b3f57
Revises: e6e652fd1654
Create Date: 2025-03-12 21:31:59.710630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f114a23b3f57'
down_revision = 'e6e652fd1654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
