"""added last checkout session

Revision ID: f685711ad2cf
Revises: aa0442f11223
Create Date: 2025-03-06 13:52:25.554174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f685711ad2cf'
down_revision = 'aa0442f11223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checkout_session_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_checkout_session_id')

    # ### end Alembic commands ###
